extends "res://tests/source_autosave_ui.gd"

func run() -> void:
	if OS.get_environment("RICHMAN4_MAP_CATALOG").is_empty():
		print("PRECONDITION_UNMET actual catalog required")
		quit(2)
		return
	var view := SubViewport.new()
	view.size = Vector2i(640,480)
	root.add_child(view)
	var ui := TitleTestUI.new()
	view.add_child(ui)
	await settle()
	ui.set_process(false)
	var definition := find_map(ui,"Game",1)
	check(ui._new_game(160,4,definition,ui._default_setup_options(4,definition)),"catalog-backed lifecycle owner")
	var game: Object = ui.game_state
	var folder := "/tmp/richman4-inventory-lifecycle-%d" % OS.get_process_id()
	var storage := CountSlots.new(folder.path_join("slots"),folder.path_join("legacy.json"))
	ui.source_save_menu.storage = storage
	ui._on_source_cards_requested()
	var before: Dictionary = game.to_dict()
	var previous := before.duplicate(true)
	previous.day = int(before.day)-1
	# Inject the already-captured daily event boundary; no core day mutation.
	ui._source_autosave.capture_transition(game,previous,before,true)
	ui._flush_source_autosave()
	check(ui._source_autosave.pending() and storage.attempts == 0,"held list defers a pending daily snapshot")
	ui._on_source_tools_requested()
	ui._on_source_load_requested()
	ui._on_new_game_pressed()
	check(ui._inventory_mode == "cards" and game.to_dict() == before,"pending checkpoint cannot replace active list or game")
	ui.source_inventory_panel.close()
	await settle()
	ui._flush_source_autosave()
	check(not ui._source_autosave.pending() and storage.attempts == 1,"list cancellation releases pending checkpoint exactly once")
	ui._refresh_from_state()
	ui._flush_source_autosave()
	check(storage.attempts == 1 and game.to_dict() == before,"refresh cannot replay daily snapshot or change core")
	var prior := auto_accept_quit
	ui._on_source_cards_requested()
	ui.source_inventory_panel.close()
	ui._on_source_tools_requested()
	check(not auto_accept_quit and ui._inventory_mode == "tools","same-frame close/reopen retains window hold")
	ui.source_inventory_panel.close()
	await settle()
	check(auto_accept_quit == prior,"same-frame reopen restores original quit policy, not intermediate false")
	ui._on_source_cards_requested()
	ui.source_inventory_panel.close()
	ui._on_source_ai_requested()
	await settle()
	check(ui.source_trustee_controller.is_open() and not auto_accept_quit,"inventory-to-trustee handoff keeps the next modal window hold")
	ui.source_trustee_controller.cancel()
	await settle()
	check(auto_accept_quit == prior,"next trustee close restores original quit policy")
	ui._on_source_ai_requested()
	ui.source_trustee_controller.cancel()
	ui._on_source_cards_requested()
	await settle()
	check(ui._source_inventory_modal_open() and not auto_accept_quit,"trustee-to-inventory handoff keeps the next modal window hold")
	ui.source_inventory_panel.close()
	await settle()
	check(auto_accept_quit == prior,"next inventory close restores original quit policy")
	ui._source_autosave.cancel()
	ui._source_autosave.capture_transition(game,previous,before,true)
	ui._on_source_cards_requested()
	check(not ui._source_inventory_modal_open(),"pending daily checkpoint refuses new held list")
	ui._source_autosave.skip()
	ui._presentation_busy = true
	ui._on_source_cards_requested()
	check(not ui._source_inventory_modal_open(),"movement refuses held list")
	ui._presentation_busy = false
	game.set_player_ai(0,true)
	ui._refresh_from_state()
	ui._on_source_tools_requested()
	check(not ui._source_inventory_modal_open(),"AI actor cannot open a human held list")
	view.queue_free()
	await settle()
	print("Source inventory lifetime checks: %d, failures: %d" % [checks,failures])
	quit(1 if failures else 0)
